namespace DungeonDefense.Web;

/// <summary>
/// Localization owned by the thin Web demo host. Gameplay/entity terminology intentionally matches
/// the production Godot UiLocalization strings without introducing a Godot dependency into Web.
/// </summary>
internal static class WebDemoLocalization
{
    public const string Japanese = "ja";
    public const string English = "en";

    private static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["loading"] = "Loading dungeon…",
        ["title"] = "Your Dungeon",
        ["start.title"] = "Awaken the Dungeon Core",
        ["start.description"] = "Shape a living dungeon, survive the forces that discover it, and raid the world beyond for the resources your domain needs to grow.",
        ["start.spirit"] = "The Core is awake. If you are ready, I will show you how to turn this empty stone into our domain.",
        ["start.new_run"] = "Start New Run",
        ["start.continue"] = "Continue (coming soon)",
        ["start.continue_unavailable"] = "Browser save/resume is not available in this Web build yet.",
        ["guide"] = "1. Choose a defense · 2. Click a highlighted cell · 3. Start the defense and watch the real simulation",
        ["invasion_demo"] = "Invasion",
        ["phase"] = "Phase",
        ["build_phase"] = "Dungeon Build",
        ["capacity"] = "Capacity",
        ["route"] = "Route",
        ["defense"] = "Defense",
        ["ready"] = "Ready",
        ["needs_fix"] = "Needs Fix",
        ["placements"] = "Placements",
        ["wave"] = "Wave",
        ["core"] = "Core",
        ["tick"] = "Tick",
        ["impact"] = "Trap / Guard / Facility",
        ["result"] = "Battle Result",
        ["result_core"] = "Core",
        ["result_trap"] = "Trap damage",
        ["result_guard"] = "Guard damage",
        ["result_facility"] = "Facility damage",
        ["result_heading"] = "Review what held, what failed, and where to rebuild.",
        ["result_core_hits"] = "Core hits",
        ["result_spells"] = "Spell uses",
        ["result_breached"] = "Breached",
        ["result_held"] = "Held",
        ["result_pressure"] = "Pressure",
        ["result_damage"] = "Damage",
        ["result_next"] = "Next",
        ["result_action_hint"] = "Return to the same dungeon to adjust the build, or replay the same setup immediately.",
        ["freeze_name"] = "Freeze",
        ["push_name"] = "Push",
        ["status_wave_start"] = "Wave {0} started",
        ["status_wave_end"] = "Wave {0} cleared",
        ["status_breached"] = "Floor B{0} breached",
        ["status_floor_entered"] = "Invaders entered floor B{0}",
        ["status_trap"] = "Trap dealt {0} damage",
        ["status_core_hit"] = "Core took {0} damage",
        ["status_defeated"] = "{0} defeated",
        ["spirit.speaker"] = "Dark Spirit",
        ["spirit.hint.guard_collapse"] = "Our defenders folded before the route did. Look at where the first one fell before adding more bodies.",
        ["spirit.hint.unused_device"] = "One of our devices barely joined the fight. Check its line of sight before spending more on it.",
        ["spirit.hint.no_trap"] = "The traps did almost nothing this time. The route may be passing them without giving them a real chance to work.",
        ["spirit.hint.core_hit"] = "They reached the Core. Find the first place pressure became a breach; that is where the next change matters most.",
        ["spirit.hint.safe"] = "The design held without a clear weak point. Change it for a new idea, not from panic.",
        ["result.hypothesis.guard_collapse"] = "The defensive line collapsed after a guard was lost. Review guard placement and support coverage.",
        ["result.hypothesis.unused_device"] = "Some facilities never contributed. Review their position and line of fire.",
        ["result.hypothesis.no_trap"] = "Placed traps did not contribute damage. Review route contact and placement timing.",
        ["result.hypothesis.core_hit"] = "The route allowed pressure to reach the Core. Reinforce the deepest contact point.",
        ["result.hypothesis.safe"] = "The defense held without critical Core pressure. Use the damage split to refine efficiency.",
        ["floor_1"] = "Floor B1",
        ["build_heading"] = "Place defenses, then start the assault.",
        ["battle_heading"] = "The edited board is passed directly into the real battle.",
        ["remove_hint"] = "Choose a placed object on the board to remove it.",
        ["place_hint"] = "Place {0}. Highlighted cells are valid under production placement rules.",
        ["place_section"] = "Build",
        ["edit_section"] = "Edit",
        ["rotate_room"] = "Rotate room 90°",
        ["remove"] = "Remove placement",
        ["reset_board"] = "Reset board",
        ["summary"] = "Build Summary",
        ["first_contact"] = "First contact",
        ["none"] = "None",
        ["trap_contacts"] = "Trap contacts",
        ["guard_coverage"] = "Guard coverage",
        ["facility_coverage"] = "Facility coverage",
        ["start_defense"] = "Start Defense",
        ["return_build"] = "Back to Build",
        ["magic"] = "Magic",
        ["freeze"] = "Freeze 20 MP",
        ["push"] = "Push 15 MP",
        ["recent_events"] = "Recent Battle Events",
        ["events_empty"] = "Start the defense to receive combat events from Core.",
        ["footer"] = "Build rules, placement validation, and combat run on the production Core/Application; combat motion is rendered from the shared Presentation Visual State.",
        ["placed"] = "Placed {0}.",
        ["removed"] = "Removed {0}.",
        ["nothing_remove"] = "There is no removable placement on this cell.",
        ["board_reset"] = "The board was reset to its initial state.",
        ["returned_build"] = "The same build is ready for editing again; battle results do not rewrite it.",
        ["run_start"] = "Start Defense",
        ["run_pause"] = "Pause",
        ["run_resume"] = "Resume",
        ["run_again"] = "Run Same Build Again",
        ["outcome_success"] = "Defense Success",
        ["outcome_failure"] = "Defense Failure",
        ["outcome_running"] = "Defending",
        ["outcome_paused"] = "Paused",
        ["kind_room"] = "Room",
        ["kind_trap"] = "Trap",
        ["kind_guard"] = "Guard",
        ["kind_facility"] = "Facility",
        ["event_wave"] = "New wave",
        ["event_spawn"] = "Invader spawned",
        ["event_trap"] = "Trap triggered",
        ["event_attack"] = "Attack",
        ["event_heal"] = "Heal",
        ["event_death"] = "Unit defeated",
        ["event_core"] = "Core took {0} damage",
        ["event_success"] = "Defense success",
        ["event_failure"] = "Defense failure",
        ["event_spell"] = "Spell cast",
    };

    private static readonly IReadOnlyDictionary<string, string> Ja = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["loading"] = "ダンジョンを読み込み中…",
        ["title"] = "あなたのダンジョン",
        ["start.title"] = "ダンジョンコアを目覚めさせる",
        ["start.description"] = "迷宮を築き、存在に気づいた者たちの侵攻を退け、外の世界へ侵攻して地下領域を成長させます。",
        ["start.spirit"] = "コアは目覚めたわ。準備ができたなら、この何もない岩盤を私たちの領域に変えるところから始めましょう。",
        ["start.new_run"] = "新規Runを始める",
        ["start.continue"] = "続きから（準備中）",
        ["start.continue_unavailable"] = "このWeb版ではブラウザ保存・再開はまだ利用できません。",
        ["guide"] = "1. 配置物を選ぶ · 2. 明るいセルを選ぶ · 3. 防衛開始で実Simulationをそのまま遊ぶ",
        ["invasion_demo"] = "侵攻",
        ["phase"] = "Phase",
        ["build_phase"] = "ダンジョン構築",
        ["capacity"] = "Capacity",
        ["route"] = "Route",
        ["defense"] = "防衛",
        ["ready"] = "開始可能",
        ["needs_fix"] = "要修正",
        ["placements"] = "配置",
        ["wave"] = "Wave",
        ["core"] = "Core",
        ["tick"] = "Tick",
        ["impact"] = "罠 / 守備 / 設備",
        ["result"] = "防衛結果",
        ["result_core"] = "コア",
        ["result_trap"] = "罠ダメージ",
        ["result_guard"] = "守備ダメージ",
        ["result_facility"] = "設備ダメージ",
        ["result_heading"] = "どこで持ちこたえ、どこから崩れたかを確認して次の構築へ。",
        ["result_core_hits"] = "コア被弾",
        ["result_spells"] = "魔法使用",
        ["result_breached"] = "突破",
        ["result_held"] = "防衛",
        ["result_pressure"] = "侵入圧",
        ["result_damage"] = "ダメージ",
        ["result_next"] = "次の行動",
        ["result_action_hint"] = "同じダンジョンへ戻って構成を調整するか、同じ構成ですぐ再戦できます。",
        ["freeze_name"] = "凍結",
        ["push_name"] = "押し戻し",
        ["status_wave_start"] = "Wave {0} 開始",
        ["status_wave_end"] = "Wave {0} 突破阻止",
        ["status_breached"] = "地下{0}階を突破されました",
        ["status_floor_entered"] = "侵入者が地下{0}階へ侵入",
        ["status_trap"] = "罠が {0} ダメージ",
        ["status_core_hit"] = "コアに {0} ダメージ",
        ["status_defeated"] = "{0} が戦闘不能",
        ["spirit.speaker"] = "闇の精霊",
        ["spirit.hint.guard_collapse"] = "経路より先に、配下の守りが崩れてる。数を増やす前に、最初の一体がどこで倒れたか見てみて。",
        ["spirit.hint.unused_device"] = "ほとんど戦えていない設備があるわ。追加する前に、射線がちゃんと通っていたか確かめましょう。",
        ["spirit.hint.no_trap"] = "今回は罠がほとんど働いていない。侵入経路が、罠に仕事をさせない通り方になっているのかも。",
        ["spirit.hint.core_hit"] = "コアまで届かれたわ。最初に圧力が突破へ変わった場所を見て。次に直すなら、そこがいちばん意味を持つ。",
        ["spirit.hint.safe"] = "はっきりした弱点は出なかった。いい形ね。焦らず、新しい狙いができた時に変えればいい。",
        ["result.hypothesis.guard_collapse"] = "守備兵の戦闘不能を起点に防衛線が崩れています。守備配置と支援範囲を見直す余地があります。",
        ["result.hypothesis.unused_device"] = "戦闘に寄与しなかった設備があります。配置位置と射線を見直す余地があります。",
        ["result.hypothesis.no_trap"] = "配置した罠がダメージへ結び付いていません。侵入経路との接触位置を見直す余地があります。",
        ["result.hypothesis.core_hit"] = "侵入圧力がコアまで到達しています。最深部の接敵地点を補強する余地があります。",
        ["result.hypothesis.safe"] = "致命的なコア圧力を受けずに防衛できました。ダメージ内訳から効率をさらに調整できます。",
        ["floor_1"] = "地下1階",
        ["build_heading"] = "配置してから防衛を開始",
        ["battle_heading"] = "構築した盤面をそのまま実戦闘へ",
        ["remove_hint"] = "削除したい配置物を盤面から選択してください。",
        ["place_hint"] = "{0} を配置します。明るいセルがproduction rule上の配置可能位置です。",
        ["place_section"] = "配置する",
        ["edit_section"] = "編集",
        ["rotate_room"] = "部屋を90°回転",
        ["remove"] = "配置を削除",
        ["reset_board"] = "盤面をリセット",
        ["summary"] = "構成サマリー",
        ["first_contact"] = "最初の接敵",
        ["none"] = "なし",
        ["trap_contacts"] = "罠接触",
        ["guard_coverage"] = "Guard coverage",
        ["facility_coverage"] = "Facility coverage",
        ["start_defense"] = "この構成で防衛開始",
        ["return_build"] = "構築に戻る",
        ["magic"] = "魔法",
        ["freeze"] = "凍結 20 MP",
        ["push"] = "押し戻し 15 MP",
        ["recent_events"] = "直近の戦況",
        ["events_empty"] = "防衛を開始するとCoreから戦闘イベントが流れます。",
        ["footer"] = "構築・配置判定・戦闘はproduction Core/Applicationをそのまま実行し、戦闘モーションはshared Presentation Visual Stateを描画しています。",
        ["placed"] = "{0}を配置しました。",
        ["removed"] = "{0}を削除しました。",
        ["nothing_remove"] = "このセルには削除できる配置物がありません。",
        ["board_reset"] = "盤面を初期状態へ戻しました。",
        ["returned_build"] = "戦闘結果を反映せず、同じ構成を再編集できます。",
        ["run_start"] = "防衛開始",
        ["run_pause"] = "一時停止",
        ["run_resume"] = "再開",
        ["run_again"] = "同じ構成でもう一度",
        ["outcome_success"] = "迎撃成功",
        ["outcome_failure"] = "迎撃失敗",
        ["outcome_running"] = "防衛中",
        ["outcome_paused"] = "一時停止",
        ["kind_room"] = "部屋",
        ["kind_trap"] = "罠",
        ["kind_guard"] = "守備兵",
        ["kind_facility"] = "設備",
        ["event_wave"] = "新しいWave",
        ["event_spawn"] = "侵入者が出現",
        ["event_trap"] = "罠が発動",
        ["event_attack"] = "攻撃",
        ["event_heal"] = "回復",
        ["event_death"] = "ユニット撃破",
        ["event_core"] = "コアに {0} ダメージ",
        ["event_success"] = "防衛成功",
        ["event_failure"] = "防衛失敗",
        ["event_spell"] = "魔法発動",
    };

    private static readonly Dictionary<string, (string En, string Ja)> BuildNames =
        new Dictionary<string, (string En, string Ja)>(StringComparer.Ordinal)
        {
            ["room.guard_2x2"] = ("Guard Room", "守備室"),
            ["room.poison_2x2"] = ("Poison Chamber", "毒室"),
            ["room.execution_2x2"] = ("Execution Chamber", "処刑室"),
            ["room.mana_2x2"] = ("Mana Chamber", "魔力室"),
            ["trap.spike"] = ("Spike Trap", "棘罠"),
            ["trap.poison"] = ("Poison Trap", "毒罠"),
            ["monster.skeleton_warrior"] = ("Skeleton Warrior", "スケルトン戦士"),
            ["monster.skeleton_archer"] = ("Skeleton Archer", "スケルトン弓兵"),
            ["facility.arrow_slit"] = ("Arrow Slit", "矢狭間"),
            ["facility.magic_eye"] = ("Magic Eye", "魔眼"),
        };

    public static string Text(string locale, string key)
    {
        var source = IsJapanese(locale) ? Ja : En;
        return source.TryGetValue(key, out var value) ? value : key;
    }

    public static string Format(string locale, string key, params object[] args)
        => string.Format(System.Globalization.CultureInfo.InvariantCulture, Text(locale, key), args);

    public static string BuildName(string locale, string definitionId)
        => BuildNames.TryGetValue(definitionId, out var names) ? (IsJapanese(locale) ? names.Ja : names.En) : definitionId;

    private static bool IsJapanese(string locale)
        => locale.StartsWith(Japanese, StringComparison.OrdinalIgnoreCase);
}
